name: Build and Push Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

env:
  IMAGE_NAME: devlableo-awx-ee
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: arc-awx-ee
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ansible-builder
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible-builder

      - name: Login to GitHub Container Registry
        run: |
          podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}

      - name: Build execution environment
        run: ansible-builder build -v3 -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }} -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest --container-runtime=podman

      - name: Push images
        run: |
          podman push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          podman push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest

# For more information on building and pushing execution environments,
# see README.md in this repository
